name: The Recreation Place
favicon: null
layout_spectrum: 0.92359
typography_spectrum: 0.69735
title: The Recreation Place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#e5c230'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
