typography_spectrum: 0.438054041005671
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.029279158916324377
  lightness: 0.739974295720458
  saturation: 0.4817397294100374
  rhythmicContrast: 0.8897696177009493
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4530410412698984
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d550eb3-dedb-4830-9086-f8f41bbf527a.png
name: The Recreation Place
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: ca2b8625-f0b4-4ef4-a7b8-67d72c70c825
    type: content
  - name: Hours of Operation
    id: 7afa53bd-898f-472f-82d6-f362024ad5ca
    type: content
  - name: Memberships
    id: 7c9573ac-0b31-4fac-8e1e-120d20644779
    type: content
  - name: Location
    id: 238ec593-b217-49cc-81dc-84f59868cf0f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e403b26f-fd1f-4240-82f4-4831bb81e900.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
