typography_spectrum: 0.36060539446771145
color:
  brandColors:
    - '#ffffff'
    - '#ffff01'
    - '#aabab9'
    - '#d3dddc'
    - '#ffff78'
  brandStrength: 0.5475730188190937
  lightness: 0.6356753725558519
  saturation: 0.20669781672768295
  rhythmicContrast: 0.8957685886416584
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.025588784366846085
analytics:
  google: null
  facebook: null
  twitter: null
name: The Recreation Place
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Memberships
    id: 7c9573ac-0b31-4fac-8e1e-120d20644779
    type: content
  - name: Hours of Operation
    id: 7afa53bd-898f-472f-82d6-f362024ad5ca
    type: content
  - name: About Us
    id: ca2b8625-f0b4-4ef4-a7b8-67d72c70c825
    type: content
  - name: Location
    id: 238ec593-b217-49cc-81dc-84f59868cf0f
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: The Recreation Place
purpose: []
