name: The Recreation Place
favicon: null
layout_spectrum: 0.57461
typography_spectrum: 0.50722
title: The Recreation Place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#e5c230'
    - '#6f6f6f'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
