layout_spectrum: 0.4946688443887979
typography_spectrum: 0.437460734276101
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.9375341068953276
  lightness: 0.8870457382872701
  saturation: 0.5744244484230876
  rhythmicContrast: 0.984610911924392
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c80103f-40f2-471d-b183-e88f46be9276.png
name: The Recreation Place
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: ca2b8625-f0b4-4ef4-a7b8-67d72c70c825
    type: content
  - name: Hours of Operation
    id: 7afa53bd-898f-472f-82d6-f362024ad5ca
    type: content
  - name: Memberships
    id: 7c9573ac-0b31-4fac-8e1e-120d20644779
    type: content
  - name: Schedule
    id: 2c24bca9-917c-4833-b6eb-233e068fac77
    type: content
  - name: Location
    id: 238ec593-b217-49cc-81dc-84f59868cf0f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e403b26f-fd1f-4240-82f4-4831bb81e900.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: The Recreation Place
description: Radically Empowered Community
purpose: []
